groups:
  - name: file changed
    rules:
      - alert: fileChanged
        expr: increase(fileChanged[1m]) > 0
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "File changed"
          description: "File changed PATH = {{ $labels.path }}"

      - alert: authenticated_command_executed
        expr: authCmdCalled == 1
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "Authenticated command was executed"
          description: "Authenticated command was executed"
